spring.application.name=WebsiteDSAApplication
server.port=6969
spring.thymeleaf.cache=false

# Increase file upload size for videos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
